{{- $controlPlane := "controller-manager" -}}
{{- $port := 443 -}}
{{- $targetPort := 9443 -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ tpl .Values.operator.name . }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: {{ tpl .Values.operator.name . }}
    app.kubernetes.io/part-of: {{ tpl .Values.operator.name . }}
  name: "{{ tpl .Values.operator.name . }}-webhooks"
spec:
  ports:
    - port: {{ $port }}
      protocol: TCP
      targetPort: {{ $targetPort }}
  selector:
    control-plane: {{ $controlPlane }}
