# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kubearchive-database-credentials
  namespace: kubearchive
  labels:
    app.kubernetes.io/name: kubearchive-database-credentials
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "${NEXT_VERSION}"
data:
  DATABASE_KIND: cG9zdGdyZXNxbA==
  DATABASE_PORT: "NTQzMg=="
  DATABASE_URL: "a3ViZWFyY2hpdmUtcncucG9zdGdyZXNxbC5zdmMuY2x1c3Rlci5sb2NhbA=="
  DATABASE_DB: "a3ViZWFyY2hpdmU="
  DATABASE_USER: "a3ViZWFyY2hpdmU="
  DATABASE_PASSWORD: "RGF0IWFiYXNdM1Bhc3MqdzByZA=="  # notsecret
