apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.kubearchive.namespace }}
{{- with .Values.kubearchive.testNamespace }}
{{- if .create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  {{- if .watch }}
  labels:
    kubearchive: watch
  {{- end }}
{{- end }}
{{- end }}
