{{- range .Values.kubearchive.watchNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Values.kubearchive.roleBinding }}
  namespace: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .role.name }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.kubearchive.serviceAccount }}
    namespace: {{ .name }}
{{- end }}
