---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kubearchive.serviceAccount }}
  namespace: {{ .Values.kubearchive.namespace }}
{{- range .Values.kubearchive.watchNamespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.kubearchive.serviceAccount }}
  namespace: {{ .name }}
{{- end }}
