# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/kubearchive.kubearchive.org_clusterkubearchiveconfigs.yaml
  - crds/kubearchive.kubearchive.org_kubearchiveconfigs.yaml
  - templates/api_server/api_server.yaml
  - templates/api_server/certificates.yaml
  - templates/api_server/role.yaml
  - templates/api_server/role_binding.yaml
  - templates/api_server/service_account.yaml
  - templates/database/database_secret.yaml
  - templates/eventing/brokers.yaml
  - templates/logging/configmap.yaml
  - templates/logging/secret.yaml
  - templates/operator/certificates.yaml
  - templates/operator/kubearchiveconfig_editor_role.yaml
  - templates/operator/kubearchiveconfig_viewer_role.yaml
  - templates/operator/leader_election_role.yaml
  - templates/operator/leader_election_role_binding.yaml
  - templates/operator/operator.yaml
  - templates/operator/role.yaml
  - templates/operator/role_binding.yaml
  - templates/operator/service.yaml
  - templates/operator/service_account.yaml
  - templates/operator/sink_filters.yaml
  - templates/operator/webhooks.yaml
  - templates/sink/role.yaml
  - templates/sink/role_binding.yaml
  - templates/sink/service_account.yaml
  - templates/sink/sink.yaml
  - templates/sink/trigger.yaml
  - templates/certificates.yaml
  - templates/namespace.yaml
