# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubearchive-operator
  namespace: kubearchive
  labels:
    app.kubernetes.io/name: kubearchive-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "${NEXT_VERSION}"
data:
  resources.yaml: |
    - selector:
        kind: "--all--"
        apiVersion: "--all--"
      workers: 3

