# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kubearchive-sink"
  namespace: kubearchive
  labels:
    app.kubernetes.io/name: "kubearchive-sink"
    app.kubernetes.io/component: sink
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "${NEXT_VERSION}"
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: kubearchive-sink
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: kubearchive-sink
      volumes:
        - name: logging-config
          configMap:
            name: kubearchive-logging
      containers:
        - name: kubearchive-sink
          image: ko://github.com/kubearchive/kubearchive/cmd/sink
          resources:
            requests:
              cpu: 200m
              # 90% of the limit
              # See recommendations at https://tip.golang.org/doc/gc-guide#Memory_limit
              memory: 230Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /data/logging
              name: logging-config
          envFrom:
            # Provide DB URL, user, password, database and port as env vars
            - secretRef:
                name: kubearchive-database-credentials
          env:
            - name: KUBEARCHIVE_ENABLE_PPROF
              value: "true"
            - name: GIN_MODE
              value: release
            - name: LOG_LEVEL
              value: INFO
            - name: KLOG_LEVEL
              value: "0"
            - name: KUBEARCHIVE_OTEL_MODE
              value: "disabled"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: ""
            - name: KUBEARCHIVE_OTLP_SEND_LOGS
              value: "false"
            - name: OTEL_GO_X_DEPRECATED_RUNTIME_METRICS
              value: "false"
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: KUBEARCHIVE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBEARCHIVE_LOGGING_DIR
              value: /data/logging
          ports:
            - containerPort: 8080
              name: sink
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            timeoutSeconds: 4
---
kind: Service
apiVersion: v1
metadata:
  name: "kubearchive-sink"
  namespace: kubearchive
  labels:
    app.kubernetes.io/name: "kubearchive-sink"
    app.kubernetes.io/component: sink
    app.kubernetes.io/part-of: kubearchive
    app.kubernetes.io/version: "${NEXT_VERSION}"
spec:
  selector:
    app: kubearchive-sink
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
