# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
name: Documentation Build
run-name: Documentation Build
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      # Checkout 'fetch-tags' does not work properly, see https://github.com/actions/checkout/issues/701
      - name: Fecth tags
        run: git fetch --tags origin
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '21'
      - name: Install Antora
        working-directory: ./docs
        run: npm ci
      - name: Generate Site
        working-directory: ./docs
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v5
        with:
          path: docs/build/site
          retention-days: 1
