---
name: Documentation Build
run-name: Documentation Build
on:
  pull_request:
    branches: [main]
jobs:
  setup:
    name: Log run details
    uses: ./.github/workflows/log_run_details.yml
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Install Antora
        working-directory: ./docs
        run: npm ci
      - name: Generate Site
        working-directory: ./docs
        run: npm run build
