# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
#
# GitLeaks: https://github.com/gitleaks/gitleaks
---
name: gitleaks
run-name: Running gitleaks check
# According to the GitHub documentation on Action secrets:
# "They are not passed to workflows that are triggered by a pull request from a fork."
# So we can't use pull_requests here since gitleaks needs GITLEAKS_LICENSE.
# According to the GitHub documentation on pull_request_target,
# that workflow can access secrets even when it is triggered from a fork.
on:
  pull_request_target:
    types: [opened, edited]
  schedule:
    - cron: "15 8 * * 1"  # Run once every Monday at ~8:15AM UTC
permissions:
  contents: read
  pull-requests: read
jobs:
  scan:
    # From: https://github.com/marketplace/actions/gitleaks
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.actor }}."
      - run: echo "Running on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Branch ${{ github.ref }} of repository ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITLEAKS_NOTIFY_USER_LIST: "@beerparty"
