# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
name: go_test_integration
run-name: Integration Tests (go)
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
permissions:
  contents: read
  pull-requests: read
jobs:
  setup:
    uses: ./.github/workflows/log_run_details.yml
  integration:
    name: KubeArchive Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Display Go version
        run: go version
      - name: Install latest kubectl
        run: |
          set -x
          curl -Lo ./kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv kubectl /usr/local/bin
      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v1
        version: v0.21.0
#      - name: Install KinD
#        run: |
#          set -x
#
#          # Disable swap otherwise memory enforcement doesn't work
#          # See: https://kubernetes.slack.com/archives/CEKK1KTN2/p1600009955324200
#          sudo swapoff -a
#          sudo rm -f /swapfile
#
#          curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.21.0/kind-$(uname)-amd64
#          chmod +x ./kind
#          sudo mv kind /usr/local/bin
      - name: Install ko
        uses: ko-build/setup-ko@v0.8
#      - name: Create KinD cluster
#        run: kind create cluster
      - name: Install KubeArchive
        run: |
          export KO_DOCKER_REPO="kind.local"
          bash hack/quick-install.sh
          bash integrations/logging/splunk/install.sh
      - name: Test Go code
        run: |
          export KO_DOCKER_REPO="kind.local"
          go test -count=1 -v ./test/integration/pagination_test.go -tags=integration -timeout 60m
