# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
name: go_test
run-name: Unit Tests (go)
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
permissions:
  contents: read
  pull-requests: read
jobs:
  gotest:
    name: "Golang testing"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.6'
      - name: Display Go version
        run: go version
      - name: Generate operator code
        run: cmd/operator/generate.sh
      - name: Build Go code
        run: go build -v ./...
      - name: Test Go code
        run: |
          export KUBEBUILDER_ASSETS=${PWD}/`cmd/operator/bin/setup-envtest use --bin-dir cmd/operator/bin -p path`
          go test -v ./...
