# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
name: go_test_integration
run-name: Integration Tests (go)
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
permissions:
  contents: read
  pull-requests: read
jobs:
  integration:
    name: KubeArchive Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
      - name: Display Go version
        run: go version
      - name: Install latest kubectl
        run: |
          set -x
          curl -Lo ./kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv kubectl /usr/local/bin
      - name: Install latest migrate
        run: |
          set -x
          curl -L https://github.com/golang-migrate/migrate/releases/latest/download/migrate.linux-amd64.tar.gz | tar xvz migrate
          chmod +x ./migrate
          sudo mv migrate /usr/local/bin
      - name: Install KinD
        run: |
          set -x

          # Disable swap otherwise memory enforcement doesn't work
          # See: https://kubernetes.slack.com/archives/CEKK1KTN2/p1600009955324200
          sudo swapoff -a
          sudo rm -f /swapfile

          curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.26.0/kind-$(uname)-amd64
          chmod +x ./kind
          sudo mv kind /usr/local/bin
      - name: Install ko
        uses: ko-build/setup-ko@v0.9
      - name: Create KinD cluster
        run: kind create cluster
      - name: Install KubeArchive
        run: |
          export KO_DOCKER_REPO="kind.local"
          bash hack/quick-install.sh
          bash integrations/logging/loki/install.sh --vector
      - name: Test Go code
        run: |
          bash test/integration/run.sh
      - name: Archive integration test results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: integration-results
