# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
name: golangci-lint
run-name: Linting Tests (golangci-lint)
on:
  workflow_dispatch:
  schedule:
    # 9:25 UTC every 1st of month
    - cron: '25 09 1 * *'
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
permissions:
  contents: read
  pull-requests: read
  checks: write
  issues: write
jobs:
  golangci:
    # See https://github.com/golangci/golangci-lint-action
    name: GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.9'
      - name: Display Go version
        run: go version
      - name: Generate operator code
        run: cmd/operator/generate.sh
      - name: Lint testing Go code
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          # When is scheduled, show all issues
          only-new-issues: ${{ github.event_name != 'schedule' }}
      - name: Notify golangci-lint failed
        uses: jayqi/failed-build-issue-action@v1
        if: failure() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.repository == 'kubearchive/kubearchive'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title-template: GolangCI Linting found errors
          label-name: kind/bug
          always-create-new-issue: true
          body-template: |
            The scheduled workflow of GolangCI Lint found some problems. We run this scheduled
            against the whole codebase, so when a PR is submitted authors do not need to deal with
            problems they did not introduce. However we need to solve those problems from time to time.
            The URL of the failed job is:

            https://github.com/kubearchive/kubearchive/actions/runs/{{ runId }}

            Run `golanci-lint` to see the errors locally, visit the worfklow run, make sure the problems
            you found locally match. Investigate if they do not match. Solve the problems and open a
            pull request to solve them.
