# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
#
# Renovate: https://github.com/renovatebot/github-action
# Action based on: https://github.com/renovatebot/github-action?tab=readme-ov-file#example-with-github-app
---
name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *"  # Run hourly at 15 minutes past the hour

jobs:
  renovate:
    if: github.repository == 'kubearchive/kubearchive'  # Don't run renovate on forks
    runs-on: ubuntu-latest
    steps:
      - name: Get kubearchive-renovate Github App Api Token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          private-key: ${{ secrets.KUBEARCHIVE_RENOVATE_PRIVATE_KEY }}
          app-id: ${{ secrets.KUBEARCHIVE_RENOVATE_APP_ID }}

      - name: Checkout KubeArchive repository
        uses: actions/checkout@v6

      - name: Run Renovate
        uses: renovatebot/github-action@v44.2.6
        with:
          token: '${{ steps.get_token.outputs.token }}'
        env:
          # run renovate on this repo
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          # renovate will generate an onboarding PR after the first run
          RENOVATE_ONBOARDING: "true"
          # username needed for Github auth (Github app name + "[bot]")
          RENOVATE_USERNAME: "kubearchive-renovate[bot]"
          # git commit author. Format is: Github app name <id+RENOVATE_USERNAME@users.noreply.github.com>
          # id can be retrieved from https://api.github.com/users/kubearchive-renovate[bot]
          RENOVATE_GIT_AUTHOR: "kubearchive-renovate <171263778+kubearchive-renovate[bot]@users.noreply.github.com>"
          # renovate will create signed commits
          RENOVATE_PLATFORM_COMMIT: "true"
