# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
name: Static Code Analysis
run-name: Static Code Analysis
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
jobs:
  setup:
    name: Log run details
    uses: ./.github/workflows/log_run_details.yml
  go-mod-tidy:
    name: go mod tidy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run 'go mod tidy'
        run: |
          go mod tidy
      - name: Fail if there are any changes
        run: |
          git diff --exit-code go.sum
          git diff --exit-code go.mod
  helm-lint:
    name: "Helm lint"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: latest
      - name: Setup chart-testing
        uses: helm/chart-testing-action@main
      - name: Run chart-testing (lint)
        run: ct lint --charts charts/kubearchive --config ct.yaml
      - name: Run helm template
        run: helm template charts/kubearchive/ --output-dir charts/generated
      - name: Run yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: false
          yamllint_comment: false
