# Copyright KubeArchive Authors
# SPDX-License-Identifier: Apache-2.0
---
name: Static Code Analysis
run-name: Static Code Analysis
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
jobs:
  go-mod-tidy:
    name: go mod tidy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.23.9'
      - name: Run 'go mod tidy'
        run: |
          go mod tidy
      - name: Fail if there are any changes
        run: |
          git diff --exit-code go.sum
          git diff --exit-code go.mod
  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Run yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: false
          yamllint_comment: false
  license-checker:
    name: License Checker
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '21'
      - name: Install License Checker
        run: npm install --global @kt3k/license-checker
      - name: Run License Checker
        run: license_checker
